## 数据来源
本研究使用的数据GSE131882来源于公共开源数据库Gene Expression Omnibus(GEO,https://www.ncbi.nlm.nih.gov/geo/)[@Barrett2012-nk]。共包含6个样本，糖尿病与对照组各三个样本，所有样本均纳入后续分析。


## 原始数据下载与处理
本研究使用prefetch(v3.1.1)将GSE75665的原始测序数据从SRA数据库中下载下来，然后使用fastq-dump将sra格式转化成fastq格式，最后使用STAR(v2.7.11b)[@Dobin2012-hs]和GRCm38参考基因组将fastq比对到参考基因组得到count数据用于后续分析。


## 差异分析
### 转录组
GSE75665使用DESeq2(v1.46.0)[@Love2014-sd]R包进行组间差异分析，并使用p值小于0.05和|log2 Fold Change|大于1为阈值筛选高原脑水肿组间差异表达基因。GSE90500使用limma(v3.62.2)[@Ritchie2015-ys]R包进行组建差异分析，并使用p值小于0.05和|log Fold Change|大于0.5为阈值筛选高原脑水肿组间差异表达的非编码RNA。


### 单细胞
为了研究糖尿病对纤维化细胞的影响，我们使用scran(v1.34.0)[@Lun2016-as]R包中的findMarkers函数对糖尿病与非糖尿病组建差异基因进行了差异分析，并使用p值小于0.05和|log2 Fold Change|大于1为阈值筛选组间差异基因。

## pyscenic
为了研究哪些转录调控因子与Inflam-TAMs, Monocyte, LA-TAMs以及M-MDSC细胞状态有关，本研究使用pyscenic[@Aibar20172017-na]进行转录调控因子分析。pyscenic 是一种用于单细胞 RNA-seq 数据的转录因子调控网络推断工具，其核心流程包括共表达网络构建、motif 富集分析和细胞活性评分三步。构建共表达网络主要为了识别潜在的转录调控因子与靶基因之间的调控关系，然后根据靶基因转录调控区域是否富集特定的转录调控因子的motif筛选出可能的直接调控关系，最后使用AUCell算法评估每个regulon在每个细胞中的活性，找到潜在的调控调控靶基因的转录调控因子。

## 细胞周期分析
本研究使用scran(v1.34.0)[@Lun2016-as]R包中的cyclone函数进行细胞周期分析。其使用成对基因比较的方式来提高分类的稳定性，这些成对的基因来源于已知细胞周期的数据集，因为在特定的细胞周期两个基因的相对表达水平比较稳定，通过多个这样的成对基因来判断细胞属于分裂的哪个时期。


## 肿瘤细胞鉴定
为识别单细胞转录组数据中的肿瘤细胞，我们采用 CopyKAT（Copy Number Karyotyping of Tumors）工具对表达矩阵进行染色体拷贝数变异（CNV）推断分析。CopyKAT 利用大规模基因表达模式推断染色体片段的拷贝数状态，并据此区分二倍体正常细胞与非整倍体肿瘤细胞。在本研究中，我们使用原始表达矩阵作为输入，运行 `copykat() `主函数，参数设定为 id.type = "S"（表示使用基因符号），ngene.chr = 5（每条染色体最少基因数），并指定 genome = "hg38" 以匹配参考基因组版本。CopyKAT 自动识别表达稳定的细胞群作为参考二倍体，并通过贝叶斯分类方法将细胞划分为“diploid”（正常）或“aneuploid”（肿瘤）类别。


## ssGSEA
ssGSEA（Single Sample Gene Set Enrichment Analysis）富集分析是一种基于单个样本的基因集富集分析方法，是对传统GSEA富集分析方法的拓展。传统的GSEA是基于组间进行的富集分析，而ssGSEA则针对单个样本计算基因集的富集分数，从而能够跟细致地评估每个样本中特定基因集的表达情况。ssGSEA 使用秩归一化的方法来处理基因表达数据。首先，对每个样本中的基因表达值进行排序，然后计算每个基因的秩值。基于这些秩值，生成每个基因集的经验累积分布函数（ECDF）。这种方法可以减少因基因表达水平差异带来的影响，使得到的富集分数具有样本间的可比性。
本研究使用GSVA(v2.0.7)[@Hnzelmann2013-is]R包算糖尿病足相关基因在所有细胞中的富集分数，然后计算每种细胞糖尿病足溃疡与非糖尿病足溃疡之间的富集分数差异，找到受糖尿病影响最大的细胞类型。


## GSEA富集分析
基因集富集分析(Gene Set Enrichment Analysis, GSEA)是一种用于统计预先定义的基因集在两种生物学状态之间表达趋势一致性检验。该方法利用差异分析结果将所有基因进行排序，在R语言中的排序公式如下：
$$order=setNames(-log0(pvalue)*sign(log2FC),symbol)$$
其中，$pvalue$表示实验与对照之间差异统计p值，$log2FC$表示实验与对照组之间相应基因表达水平的差异倍数，并取以2为低的对数,$symbol$代表基因的ID。
然后使用排序后的基因以及预先定义好的基因集使用clusterProfiler(v4.14.6)[@Xu2024-us]包中的函数GSEA进行富集分析，其中几个重要的参数设置为eps=0，minGSSize=10，maxGSSize=1000，其余使用默认参数。使用p值和NES（normalized enrich score）分别选择在糖皮质激素诱导的骨质疏松与对照组中富集的前两个通路并使用R包GseaVis(v0.1.0)[@Jun2025-yy]进行可视化。


## 可变剪切分析
rMATS是一种计算工具，用于从RNA-Seq数据中检测差异性可变剪接事件。MATS的统计模型计算P值和假阳性率，以判断在两种条件下，一个基因的异构体比例差异是否超过用户定义的阈值。通过RNA-Seq数据，rMATS能够自动检测和分析与所有主要类型的可变剪接模式相对应的可变剪接事件。rMATS可以处理来自配对和非配对的有重复样本的RNA-Seq数据。

rMATS可识别的可变剪切事件有5种：1. skipped exon (SE)外显子跳跃。2.lternative 5' splice site (A5SS)第一个外显子可变剪切。3. alternative 3' splice site (A3SS)最后一个外显子可变剪切。4. mutually exclusive exons (MXE)外显子选择性跳跃。5. retained intron (RI)内含子滞留。


## miRNA-mRNA调控网络分析
starBase(ENCORI, https://rnasysu.com/encori/)是一个综合的RNA互作分析平台，其通过整合CLIP-seq和degradome-seq等高通量测序技术的数据可以为研究人员提供miRNA，degradome RNA以及RBP RNA等调控网络分析。本研究通过提取GSE90500数据集中获得的差异表达miRNA且可以调控关键基因的miRNA来分析哪些非编码RNA可以调控关键基因，并且使用ggraph(v2.2.1)[@Thomas2024-su]对该调控网络进行了可视化。


## 生存分析
生存分析是一种用于分析生存时间和生存状态与各种与生存状态相关因素之间关系的统计方法。常用于分析的因素有性别、年龄、疾病分级信息、基因表达水平以及药物治疗信息等。X轴通常表示时间，可以是天、月或者年为单位。Y轴表示生存概率，即对应时间点的存活下来的概率。曲线通常从左上角开始，随着时间的推移，曲线逐渐下降直至0%。曲线上可能会显示置信区间，这表示生存概率在对应时间点的可能取值范围。如果图中包含多条曲线，每条曲线表示代表不同的组别，且曲线下面积越大表示该组的总体生存时间越长。本研究以风险评分的高低风险组为分组变量，以患者的生存时间和状态为相应变量分析两组之间的生存状态是否有显著差异。


## 单因素和多因素Cox分析
我们使用临床信息，如性别、年龄、肿瘤T分期、M分期以及N分期等信息进行高低风险组之间单因素和多因素Cox分析。并使用forestplot(v3.1.5)[@Max2024-ay]R包将每个变量的风险值等信息可视化。


## GO和KEGG富集分析
GO(Gene Ontology)和KEGG都是包含根据特定的生物学功能或者生物学过程定义的基因集。GO和KEGG富集分析就是使用超几何分布检验在给定背景基因情况下某些基因集中的基因出现在差异基因集中的频率是否有显著变化。从而从更高维度检查实验组与对照组之间哪些生物学过程或者功能发生了显著改变。本研究使用clusterProfiler(v4.14.6)[@Xu2024-us]R包对高原脑水肿组间差异基因和炎症相关基因的交集基因进行GO和KEGG富集分析，用于研究高原脑水肿相关的炎症相关基因主要有哪些生物学功能。


## 分子对接
本研究使用gluedocking(v0.1.0)[@Beihao2025-ja]R包进行分子对接研究，并使用PyMol(v3.1.6.1)软件将对接结果进行可视化。


## 突变负荷分析
为了比较高低风险组之间的突变符合，我们使用TCGAbiolinks(v2.32.0)[@Colaprico2015-ua]从TCGA数据库中将高低风险组的单核苷酸突变信息下载下来，并使用maftools(v2.20.0)[@Mayakonda2018-hu]将高低风险组前20个高突变的基因展示出来。此外，我们还计算了高低风险组之间每个样本的肿瘤突变负荷(tumor mutation burden, TMB)，并使用ggplot2(v3.5.1)[@Hadley2016-la]对上述结果进行了可视化。


## 机器学习筛选特征基因
为了筛选哪些基因与糖皮质激素诱导的骨质疏松最相关，我们使用LASSO回归、RandomForest以及SVM-RFE三种机器学习算法筛选糖皮质激素诱导的骨质疏松特征基因[@Friedman2010;@Andy2002;@David2024]。
LASSO回归通过引入L1正则化项，能够自动地对特征进行筛选。其核心机制是将某些特征的系数压缩为零，从而实现特征选择。L1正则化项对系数的惩罚是基于绝对值，这使得LASSO回归倾向于将某些系数压缩为零，而不是像L2正则化（岭回归）那样仅仅缩小系数的大小。当λ增大时，正则化项的惩罚作用增强，更多的系数会被压缩为零，从而实现特征筛选。
随机森林（Random Forest）是一种集成学习方法，它通过构建多个决策树并将它们的预测结果进行汇总来提高模型的准确性和稳健性。随机森林不仅是一种强大的预测工具，还可以用于特征选择，即识别对模型预测结果影响最大的特征。
SVM-RFE算法的主要思想是通过反复训练模型并删除最不重要的特征，从而找到最佳的特征子集。在每一轮迭代中，删除的特征是通过计算特征的重要性得出的，这样可以确保每次删除的特征对模型的影响较小。该算法的优势在于它可以提高模型的泛化能力，并且可以在训练过程中自动选择特征，无需手动调节参数。
三种机器学习算法取筛选的结果取交集，交集基因认为是糖皮质激素诱导的骨质疏松的特征基因。


## ROC分析
ROC曲线即受试者特征工作曲线，主要用来评价某种指标的分类或者诊断效果。为了检查机器学习筛选的关键基因的分类能力，我们使用4个关键基因的表达水平和pROC(v1.18.5)[@Xavier2011-is]R包进行了ROC分析。


# 诊断列线图
列线图（Alignment Diagram），也叫诺莫图（Nomogram图），是一种基于多因素回归分析的图形工具。它把多个预测指标整合在一起，用带有刻度的线段表示，从而展示预测模型中各个变量之间的关系。使用rms(v8.0.0)[@Frank2025-ha]和rmda(v1.6)[@Marshall2018-na]R包，我们构建了一个利用特征基因个性化预测生存风险的列线图。此外，我们绘制了决策曲线来验证列线图预测生存状态的准确性和可靠性。


## 转录调控网络
为了研究5个靶点基因的转录调控网络，我们从hTarget(https://guolab.wchscu.cn/hTFtarget/#!/)网站下载了所有的转录调控因子及其调控信息，并使用babelgene(v22.9)[@Igor2022-ys]将其转换成小鼠的基因，然后筛选5个关键基因的转录调控因子信息，并使用ggraph(v2.2.1)[@Thomas2024-su]对调控网络进行了可视化。


## 一致性聚类分析(Consensus Clustering)
一致性聚类(consensus clustering)是一种无监督聚类方法，其核心思想是通过多次随机采样与聚类操作来评估和确定数据集中聚类结果的稳定性和一致性。其核心步骤为从原始数据中多次随机抽取子样本，构建多个数据子集。然后选择不同的聚类数目对每个子集进行聚类，并记录每个样本在多次聚类过程中的归属。计算两个样本被分配到同一聚类的频率，生成一致性聚类矩阵，矩阵的取值范围为0-1，表示样本之间的聚类一致性。最后使用累计分布函数(Cumulative Distribution Function, CDF)和曲线下面积变化折线图评估聚类最稳定的k值。本研究使用consensusClusterPlus(v1.70.0)[@Wilkerson2010-la]R包对所有样本进行一致性聚类，用于寻找疾病可能存在的亚型。


## 蛋白互作分析
STRING数据库(https://string-db.org/)[@Szklarczyk2022-ta]包含了蛋白之间关联的各种信息的综合平台。为了研究亚型间差异基因与亚型相关模块交集基因之间的关系，我们使用STRING数据库对两者的交集基因进行了蛋白互作分析，然后使用7种重要性算法对蛋白进行排序，分别选取前150个基因，然后取交集得到亚型间关键基因，并使用ggVennDiagram(v1.5.2)[@Chun2024-ta]R包对交集基因进行了可视化。


## CIBERSORT
### 免疫浸润分析
肿瘤内部和周围往往聚集着大量的免疫细胞，这些免疫细胞之间存在着千丝万缕的关系。免疫浸润的分析，本质上就是研究组织中不同免疫细胞的构成比例。本次分析采用CIBERSORT算法评估转录组样本中不同免疫细胞的构成情况。 CIBERSORT(v0.1.0)[@Erjie2025-js]是基于线性支持向量回归的原理对免疫细胞的表达矩阵进行去卷积的一个工具，其基于训练集样本基因的表达水平，对22种免疫细胞构成比例进行了估算。为了研究亚型之间免疫细胞浸润的差异，我们对不同免疫细胞在亚型之间的浸润水平进行了秩和检验（Wilcox test），以统计在亚型之间浸润水平有显著差异的免疫细胞。


### 去卷积分析
本研究使用CIBERSORT(v0.1.0)[@Erjie2025-js]和PBMC单细胞测序数据为参照评估GSE75665数据中高原脑水肿患者相对与健康个体外周血中的细胞构成是否出现显著变化。


## 药物基因互作分析
药物基因互作数据库是一个整合了DrugBank，PharmGKB，ChEMBL，DrugTargetCommons等数据库中药物基因互作关系的综合数据库。这种互作关系可能是药物与基因组DNA互作影响基因表达，也可能是药物与基因产物互作进而调控其活性。为了研究哪些药物可一调控MDK转录调控因子的表达或者功能，我们从DGIdb(https://dgidb.org/)数据库下载了所有可能与上述转录调控因子互作的药物，并使用网络图对其互作关系进行了可视化。


## 分子对接
本研究使用gluedocking(v0.1.0)[@Beihao2025-ja]R包进行分子对接研究，首先我们从PubChem（https://pubchem.ncbi.nlm.nih.gov/）和PDB（https://www.rcsb.org/）数据库中将小分子化合物的结构信息和蛋白的晶体结构信息下载下来，并将其中将蛋白结构其中的非蛋白成分去除，然后将小分子化合物与蛋白进行对接，并使用PyMol软件对对接结果进行可视化。

## 药物敏感性分析
本研究使用oncoPredict(v1.2)[@Authors2025-ta]R包对糖皮质激素诱导的骨质疏松组与对照组之间进行药物敏感性分析，其原理是利用已知的细胞系表达矩阵和药物敏感性信息作为训练集构建模型，然后利用该模型对输入的基因表达矩阵中的样本进行药物敏感性预测。本研究使用oncoPredict提供的CTRP2_Expr (TPM, not log transformed).rds基因表达数据和CTRP2_Res.rds表型数据为训练集，使用GSE276391表达矩阵为输入数据，并预测GSE276391糖皮质激素诱导的骨质疏松组与对照组组内每个样本对545种药物的敏感性（半抑制浓度，IC50），并使用ggplot2(v3.5.1)[@Hadley2016-ma]和pheatmap(v1.0.12) [@Raivo2019-ia]R包绘制了与特征基因表达水平显著相关的前50个药物的相关性热图。


## WGCNA
WGCNA(weighted gene co-expression network analysis，加权基因共表达网络分析)是一种分析多个样本基因表达模式的分析方法，可将表达模式相似的基因进行聚类，并分析模块与特定性状或表型之间的关联。因此，在疾病以及其他性状与基因关联分析等方面的研究中被广泛应用，不少文章运用该方法来寻找潜在生物标志物以及药物靶点。然后使用模块特征值(module eigengene)代表对应的模块基因，接着计算模块与模块之间的相关性以及模块与样本性状之间的相关性，从而筛选出与性状高度相关的模块，并选取模块中的基因进行后续研究。 本研究选取样本间变异系数前75%的基因进行WGCNA分析，我们用R包WGCNA(v1.73)[@Langfelder2008-ls]以TLS富集分数作为表型性状。首先提取基因的表达数据，然后使用pickSoftThreshold函数进行网络拓扑分析，计算软阈值和无标度拟合指数(范围从1到30)，得到无标度拓扑矩阵，根据R^2^(无标度拟合指数)大于 0.85，选择软阈值。其次，根据上述选择的软阈值，计算邻接矩阵，并进一步构造拓扑重叠矩阵(TOM)。TOM矩阵中的值反映了两个基因水平之间的共表达关系的相似性。然后，使用flashClust函数进行层次聚类分析，并使用动态切割树算法(dynamic cut)切割基因聚类树，设置参数minModuleSize(minModuleSize：每个模块至少包含基因数目)将基因聚集为模块；同时，对每个模块进行随机分颜色，并采用主成分分析的方法计算每个模块的模块特征向量。最后，利用模块特征向量计算模块与表型的相关性，选取高相关性并且p值小于0.05的模块作为表型相关模块，模块基因作为WGCNA识别的与亚群标型高度相关的基因。


## 单细胞数据分析
本研究使用GSE131882单细胞数据集用于单细胞方面的分析。首先，使用DropletUtils(v1.24.0)[@Griffiths2018-hu]R包将单细胞数据读入到R语言环境，使用测序深度（total counts）、检测到的基因个数（number of detected features）以及比对到线粒体基因的UMI数占总基因UMI数的比例（mitochandrial percentage）为参数筛选掉低质量的细胞。然后分别使用scran(v1.34.0)[@Lun2016-as], batchelor(v1.22.0)[@Haghverdi2018-ji], bluster(v1.16.0)[@Aaron2020-nk], scater(v1.34.1)[@McCarthy2017-yd]等R 包对细胞进行标准化（normalization）、检查高变异基因（high variable gene detection）、去批次效应（remove batch effect）、降维（dimension reduction）、聚类（clustering）以及使用已知的marker基因进行细胞类型注释（cell type annotation）。

## 肿瘤细胞鉴定
infercnv(v1.22.0)[@Klarman2019-hs]是一个专为但细胞测序数据设计的R包，用于推断拷贝数变异（copy number variation, CNV）,从而识别样本中的恶性肿瘤细胞。它通过比较目标细胞与参考细胞基因表达差异来推测染色体大片段的扩增或者缺失。本研究使用免疫细胞为参考细胞来识别HPV阳性与阴性样本中哪些上皮细胞cluster属于肿瘤细胞。

## 细胞通讯分析
本研究使用CellChat(v2.1.2)[@Suoqin2025-ya]进行糖尿病与非糖尿病足底溃疡样本之间细胞通讯分析。首先，我们比较了糖尿病与非糖尿病组间所有细胞总体通讯数量和强度的变化，然后比较了相对于糖尿病与非糖尿病足细胞之间通讯数量和强度的变化，最后我们选择分析了通讯数量和强度变化较大的纤维化细胞(Fibroblast)与周细胞(Pericyte)之间有显著变化的配受体对，并用热图展示了参与上述配受体对的基因在两种细胞之间的表达水平。


## 拟时序分析
拟时序分析的主要假设是在某一时刻同一个组织中的某种细胞会处于多个连续状态，而细胞状态的不同主要体现在基因表达水平的改变，通过分析基因表达水平在不同细胞之间的分布状态，从而构建出细胞状态分布轨迹。本研究使用monocle(v2.32.0)[@Trapnell2014-ka]对高表达预后相关基因的的T细胞(CD4+ T Cells， CD+ T Cells)进行拟时序分析，用于研究T细胞分化状态与高低风险组之间的关系。首先将CD4+ T Cells和CD8+ T Cells从单细胞数据集中提取出来，使用newCellDataSet函数构建monocle 识别的数据结构。然后进行数据的标准化，检查高变异基因，降维，以及对细胞进行排序。


## 细胞分化潜能分析
CytoTRACE2（v1.1.0）[@Minji2025-ha]是一种用于计算单细胞分化潜能的工具。它通过分析单细胞RNA测序数据中基因表达的稀疏性来评估细胞的分化状态。CytoTRACE2的核心思想是，分化程度较低的细胞通常具有更高的基因表达多样性，而分化程度较高的细胞则表现出更低的基因表达多样性。通过计算每个细胞的基因表达稀疏性，CytoTRACE2能够为每个细胞分配一个分化潜能评分，从而揭示细胞在发育或疾病过程中的分化状态。本研究使用CytoTRACE2对内皮细胞进行分化潜能分析，并使用ggplot2(v3.5.1)[@Hadley2016-la]对结果进行了可视化。

## 细胞周期分析


## SAHMI
SAHMI (Single-cell Analysis of Host-Microbiome Interactions)[@Ghaddar2023] 是一个专门用于从标准单细胞转录组测序（scRNA-seq）数据中提取、去噪并分析微生物信号的生物信息学工具。其核心价值在于无需额外的实验修改，即可在单细胞分辨率下研究宿主细胞与其关联微生物的相互作用。SAHMI 利用标准的 scRNA-seq 流程在捕获宿主细胞 mRNA 的同时，也会无意中捕获到与其物理关联的微生物核酸。其利用基于 k-mer 的分类器（Kraken2Uniq）将未匹配到宿主基因组的 reads 与微生物参考数据库进行比对。由于微生物信号稀疏且易受环境污染影响，SAHMI 引入了k-mer 相关性测试 (kCT)。其原理是：真正的微生物信号其“总 k-mer 数”与“唯一 k-mer 数”应具有显著相关性，而随机噪声或污染则不具备此特征。


## 代谢活性分析
为了研究那些代谢通路在关键细胞中的代谢活性在COPD发生后发生显著改变，本研究使用scMetabolism()[@]在单细胞水平分析了所有代谢通路在关键细胞中的活性，并找出COPD发生后显著改变的的代谢通路。


## 调控网络分析
NicheNet(v2.2.0)[@Robin2019-ia]是一种用于预测细胞间通讯如何影响基因表达的工具。它的核心思想是整合配体-受体相互作用、信号通路和转录调控网络，构建一个完整的细胞通讯网络，从而预测哪些配体可能影响目标细胞的基因表达。其不有别于`CellChat`和`CellPhoneDB`，上述两个工具仅可以预测细胞表面的互作，而NicheNet可以推测这些互作可能同调控哪些基因的表达。本研究使用其研究细胞基质中哪些配体可能通过调控哪些转录调控因子进而调控目的基因MDK在纤维细胞中的表达。


## 空间转录组数据分析
本研究使用Giotto(v4.2.1)[@Ruben2020-ha]进行空间转录组的数据分析。首先去除不在组织上的spots，然后添加spots和基因的统计信息，并利用这些统计信息筛选掉低质量的spots和低表达基因，然后对数据进行标准化，筛选高变异基因，最后进行降维和聚类。此外，我们还展示了筛选到的金樱子和芡实靶点基因在空间上的表达模式。



## 统计分析
本项目的所有分析均在R(v4.4.1)中完成，p值小于0.05认为具有统计显著性。连续型变量使用t.test(正态)和Wilcoxon检验(非正态)，离散型变量使用卡方检验。
